parameters:
    open_orchestra_media.display_media_manager.class: OpenOrchestra\Media\DisplayMedia\DisplayMediaManager
    open_orchestra_media.display_media.image.class: OpenOrchestra\Media\DisplayMedia\Strategies\ImageStrategy
    open_orchestra_media.display_media.pdf.class: OpenOrchestra\Media\DisplayMedia\Strategies\PdfStrategy
    open_orchestra_media.display_media.video.class: OpenOrchestra\Media\DisplayMedia\Strategies\VideoStrategy
    open_orchestra_media.display_media.audio.class: OpenOrchestra\Media\DisplayMedia\Strategies\AudioStrategy

services:
    open_orchestra_media.display_media_manager:
        class: %open_orchestra_media.display_media_manager.class%
        arguments:
            - @router
    open_orchestra_media.display_media.image:
        class: %open_orchestra_media.display_media.image.class%
        arguments:
            - @request_stack
            - %open_orchestra_media.media_domain%
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.pdf:
        class: %open_orchestra_media.display_media.pdf.class%
        arguments:
            - @request_stack
            - %open_orchestra_media.media_domain%
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.video:
        class: %open_orchestra_media.display_media.video.class%
        arguments:
            - @request_stack
            - %open_orchestra_media.media_domain%
            - @translator
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.audio:
        class: %open_orchestra_media.display_media.audio.class%
        arguments:
            - @request_stack
            - %open_orchestra_media.media_domain%
        calls:
            - [ setContainer, [ @service_container ]  ]
        tags:
            - { name: open_orchestra_media.display_media.strategy }
