parameters:
    open_orchestra_media.display_media_manager.class: OpenOrchestra\Media\DisplayMedia\DisplayMediaManager
    open_orchestra_media.display_media.image.class: OpenOrchestra\Media\DisplayMedia\Strategies\ImageStrategy
    open_orchestra_media.display_media.pdf.class: OpenOrchestra\Media\DisplayMedia\Strategies\PdfStrategy
    open_orchestra_media.display_media.video.class: OpenOrchestra\Media\DisplayMedia\Strategies\VideoStrategy

services:
    open_orchestra_media.display_media_manager:
        class: %open_orchestra_media.display_media_manager.class%
        arguments:
            - @router
    open_orchestra_media.display_media.image:
        class: %open_orchestra_media.display_media.image.class%
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.pdf:
        class: %open_orchestra_media.display_media.pdf.class%
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.video:
        class: %open_orchestra_media.display_media.video.class%
        tags:
            - { name: open_orchestra_media.display_media.strategy }
