parameters:
    open_orchestra_media.display_media_manager.class: OpenOrchestra\Media\DisplayMedia\DisplayMediaManager
    open_orchestra_media.display_media.image.class: OpenOrchestra\Media\DisplayMedia\Strategies\ImageStrategy
    open_orchestra_media.display_media.pdf.class: OpenOrchestra\Media\DisplayMedia\Strategies\PdfStrategy
    open_orchestra_media.display_media.video.class: OpenOrchestra\Media\DisplayMedia\Strategies\VideoStrategy
    open_orchestra_media.display_media.audio.class: OpenOrchestra\Media\DisplayMedia\Strategies\AudioStrategy
    open_orchestra_media.display_media.default.class: OpenOrchestra\Media\DisplayMedia\Strategies\DefaultStrategy

services:
    open_orchestra_media.display_media_manager:
        class: '%open_orchestra_media.display_media_manager.class%'
        arguments:
            - '@open_orchestra_media.display_media.default'
    open_orchestra_media.display_media.image:
        class: '%open_orchestra_media.display_media.image.class%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.pdf:
        class: '%open_orchestra_media.display_media.pdf.class%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.video:
        class: '%open_orchestra_media.display_media.video.class%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.audio:
        class: '%open_orchestra_media.display_media.audio.class%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: open_orchestra_media.display_media.strategy }
    open_orchestra_media.display_media.default:
        class: '%open_orchestra_media.display_media.default.class%'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: open_orchestra_media.display_media.strategy }
