parameters:
    php_orchestra_media.manager.image_resizer.class: PHPOrchestra\Media\Manager\ImageResizerManager
    php_orchestra_media.manager.gaufrette.class: PHPOrchestra\Media\Manager\GaufretteManager

services:
    php_orchestra_media.manager.image_resizer:
        class: %php_orchestra_media.manager.image_resizer.class%
        arguments:
            - %php_orchestra_media.tmp_dir%
            - %php_orchestra_media.thumbnail.configuration%
            - %php_orchestra_media.resize.compression_quality%
            - @event_dispatcher

    php_orchestra_media.manager.gaufrette:
        class: %php_orchestra_media.manager.gaufrette.class%
        arguments:
            - @knp_gaufrette.filesystem_map
            - %php_orchestra_media.filesystem%
