parameters:
    open_orchestra_media.manager.image_resizer.class: OpenOrchestra\Media\Manager\ImageResizerManager

services:
    open_orchestra_media.manager.image_resizer:
        class: %open_orchestra_media.manager.image_resizer.class%
        arguments:
            - %open_orchestra_media.tmp_dir%
            - %open_orchestra_media.thumbnail.configuration%
            - %open_orchestra_media.resize.compression_quality%
            - @event_dispatcher
            - @open_orchestra_media.imagick.factory
