parameters:
    open_orchestra_media.bbcode.definition.media.class: OpenOrchestra\MediaBundle\BBcode\MediaCodeDefinition
    open_orchestra_media.bbcode.definition.media_without_format.class: OpenOrchestra\MediaBundle\BBcode\MediaWithoutFormatCodeDefinition
    open_orchestra_media.bbcode.code_definitions.class: OpenOrchestra\MediaBundle\BBcode\MediaBundleBBcodeCollection
    open_orchestra_media.imagick.factory.class: OpenOrchestra\Media\Imagick\OrchestraImagickFactory
    open_orchestra_media.ffmpeg_movie.frame.class: OpenOrchestra\Media\FFmpegMovie\FFmpegMovieFrame

services:
    open_orchestra_media.bbcode.definition.media:
        class: %open_orchestra_media.bbcode.definition.media.class%
        arguments:
            - @open_orchestra_media.repository.media
            - @open_orchestra_media.display_media_manager
            - @templating
    open_orchestra_media.bbcode.definition.media_without_format:
        class: %open_orchestra_media.bbcode.definition.media_without_format.class%
        arguments:
            - @open_orchestra_media.repository.media
            - @open_orchestra_media.display_media_manager
            - @templating
    open_orchestra_media.bbcode.code_definitions:
        class: %open_orchestra_media.bbcode.code_definitions.class%
        arguments:
            - @open_orchestra_media.bbcode.definition.media
            - @open_orchestra_media.bbcode.definition.media_without_format
        tags:
            - { name: open_orchestra_bbcode.code_definitions }
    open_orchestra_media.imagick.factory:
        class: %open_orchestra_media.imagick.factory.class%
    open_orchestra_media.ffmpeg_movie.frame:
        class: %open_orchestra_media.ffmpeg_movie.frame.class%
