parameters:
    open_orchestra_media.subscriber.generate_image.class: OpenOrchestra\Media\EventSubscriber\GenerateImageSubscriber
    open_orchestra_media.subscriber.upload_image.class: OpenOrchestra\Media\EventSubscriber\UploadImageSubscriber
    open_orchestra_media.subscriber.media.class: OpenOrchestra\MediaBundle\EventSubscriber\MediaSubscriber

services:
    open_orchestra_media.subscriber.generate_image:
        class: %open_orchestra_media.subscriber.generate_image.class%
        arguments:
            - @open_orchestra_media.manager.image_resizer
        tags:
             - { name: kernel.event_subscriber }
    open_orchestra_media.subscriber.upload_image:
        class: %open_orchestra_media.subscriber.upload_image.class%
        arguments:
            - @open_orchestra_media.manager.gaufrette
        tags:
             - { name: kernel.event_subscriber }
    open_orchestra_media.subscriber.media:
        class: %open_orchestra_media.subscriber.media.class%
        arguments:
            - @open_orchestra_display.manager.cacheable
            - @open_orchestra_base.manager.tag
        tags:
            - { name: kernel.event_subscriber }
