parameters:
    open_orchestra_media.subscriber.generate_image.class: OpenOrchestra\Media\EventSubscriber\GenerateImageSubscriber
    open_orchestra_media.subscriber.upload_image.class: OpenOrchestra\Media\EventSubscriber\UploadImageSubscriber
    open_orchestra_media.subscriber.delete_media.class: OpenOrchestra\Media\EventSubscriber\DeleteMediaSubscriber

services:
    open_orchestra_media.subscriber.generate_image:
        class: %open_orchestra_media.subscriber.generate_image.class%
        arguments:
            - @open_orchestra_media.manager.image_resizer
        tags:
             - { name: kernel.event_subscriber }
    open_orchestra_media.subscriber.upload_image:
        class: %open_orchestra_media.subscriber.upload_image.class%
        arguments:
            - @open_orchestra_media_file.manager.uploaded_media
        tags:
             - { name: kernel.event_subscriber }
    open_orchestra_media.subscriber.delete_media:
        class: %open_orchestra_media.subscriber.delete_media.class%
        arguments:
            - @open_orchestra_media_file.manager.uploaded_media
            - %open_orchestra_media.thumbnail.configuration%
        tags:
            - { name: kernel.event_subscriber }
