parameters:
    open_orchestra_media.thumbnail_manager.class: OpenOrchestra\Media\Thumbnail\ThumbnailManager
    open_orchestra_media.thumbnail.pdf_to_image.class: OpenOrchestra\Media\Thumbnail\Strategies\PdfToImageManager
    open_orchestra_media.thumbnail.video_to_image.class: OpenOrchestra\Media\Thumbnail\Strategies\VideoToImageManager
    open_orchestra_media.thumbnail.image_to_thumbnail.class: OpenOrchestra\Media\Thumbnail\Strategies\ImageToThumbnailManager

services:
    open_orchestra_media.thumbnail_manager:
        class: %open_orchestra_media.thumbnail_manager.class%
    open_orchestra_media.thumbnail.pdf_to_image:
        class: %open_orchestra_media.thumbnail.pdf_to_image.class%
        arguments:
            - %open_orchestra_media.tmp_dir%
            - %media.directory%
        tags:
            - { name: open_orchestra_media.thumbnail.strategy }
    open_orchestra_media.thumbnail.video_to_image:
        class: %open_orchestra_media.thumbnail.video_to_image.class%
        arguments:
            - %open_orchestra_media.tmp_dir%
            - %media.directory%
        tags:
            - { name: open_orchestra_media.thumbnail.strategy }
    open_orchestra_media.thumbnail.image_to_thumbnail:
        class: %open_orchestra_media.thumbnail.image_to_thumbnail.class%
        arguments:
            - %open_orchestra_media.tmp_dir%
            - @event_dispatcher
        tags:
            - { name: open_orchestra_media.thumbnail.strategy }
