parameters:
    open_orchestra_media.twig.display_media.extension.class: OpenOrchestra\MediaBundle\Twig\DisplayMediaExtension

services:
    open_orchestra_media.twig.display_media.extension:
        class: %open_orchestra_media.twig.display_media.extension.class%
        arguments:
            - @open_orchestra_media.display_media_manager
            - @open_orchestra_media.repository.media
        tags:
            - { name: twig.extension }
