parameters:
    open_orchestra_media.twig.display_media.extension.class: OpenOrchestra\Media\Twig\DisplayMediaExtension

services:
    open_orchestra_media.twig.display_media.extension:
        class: %open_orchestra_media.twig.display_media.extension.class%
        arguments:
            - @open_orchestra_media.display_media_manager
            - @open_orchestra_media.repository.media
            - @request_stack
            - @open_orchestra_media.helper.media_with_format_extractor
        tags:
            - { name: twig.extension }
