language: php

php:
  - 5.4

cache:
  directories:
    - ~/.composer/cache

sudo: false

before_install:
  - printf "\n" |pecl install imagick
  - phpenv config-add .travis.php.ini

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=d8790063c357cd94fe7a2e7c15c00b60f3363435a558d5fa16a5874e383a61da ./bin/test-reporter
