language: php

php:
  - 5.5

sudo: false

cache:
  directories:
    - ~/.composer/cache

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: d8790063c357cd94fe7a2e7c15c00b60f3363435a558d5fa16a5874e383a61da 

after_script:
  - ./bin/test-reporter
