parameters:
#    php_orchestra_indexation.example.class: PHPOrchestra\IndexationBundle\Example

services:
#    php_orchestra_indexation.example:
#        class: %php_orchestra_indexation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
