parameters:
    php_orchestra_indexation.index_helper.class: PHPOrchestra\CMSBundle\Helper\IndexHelper

services:
    phporchestra_indexation.index_helper:
        class: %php_orchestra_indexation.index_helper.class%
        arguments: [@router, @mandango, @solarium.client]
