parameters:
    open_orchestra_media_model.type.folder_choice.class : OpenOrchestra\MediaModelBundle\Form\Type\Component\FolderChoiceType

services:
    open_orchestra_media_model.type.folder_choice:
        class: '%open_orchestra_media_model.type.folder_choice.class%'
        arguments:
            - '@open_orchestra_backoffice.context_backoffice_manager'
            - '@security.authorization_checker'
            - '%open_orchestra_media.document.media_folder.class%'
        tags:
            - { name: form.type, alias: oo_folder_choice}
