parameters:
    open_orchestra_media.doctrine_listener.move_uploaded_file.class: OpenOrchestra\Media\EventListener\MoveUploadedFileListener
services:
    open_orchestra_media.doctrine_listener.move_uploaded_file:
        class: %open_orchestra_media.doctrine_listener.move_uploaded_file.class%
        arguments:
            - @open_orchestra_media_admin.manager.save_media
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
            - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
