resolve_target_documents:
    OpenOrchestra\Media\Model\FolderInterface: %open_orchestra_media.document.folder.class%
    OpenOrchestra\Media\Model\MediaFolderInterface: %open_orchestra_media.document.media_folder.class%
    OpenOrchestra\Media\Model\MediaInterface: %open_orchestra_media.document.media.class%
