parameters:
#    php_orchestra_model.example.class: PHPOrchestra\ModelBundle\Example

services:
#    php_orchestra_model.example:
#        class: %php_orchestra_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
